### ISSUE TITLE
Support for Python < 3.10

### ISSUE THREAD

**Issue by tanchihpin0517** [CPJKU/beat_this#2]
I got this error while running `beat_this` with Python3.8 and Python3.9:
```
  File "/home/tanch/workspace/mirtoolkit/src/mirtoolkit/beat_this.py", line 2, in <module>
    from beat_this.inference import File2Beats
  File "/home/tanch/.myenv/local/conda/envs/test3.8/lib/python3.8/site-packages/beat_this/inference.py", line 9, in <module>
    from beat_this.model.beat_tracker import BeatThis
  File "/home/tanch/.myenv/local/conda/envs/test3.8/lib/python3.8/site-packages/beat_this/model/beat_tracker.py", line 17, in <module>
    class BeatThis(nn.Module):
  File "/home/tanch/.myenv/local/conda/envs/test3.8/lib/python3.8/site-packages/beat_this/model/beat_tracker.py", line 132, in BeatThis
    head_dim: int | None = 32,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
It seems that `beat_this` doesn't support Python below 3.10. Do you have any plan for the compatibility?

**Comment by fosfrancesco** [comment]
Yes, this is due to the type hint operator ```|``` which was only introduced in Python 3.10.
We are discussing whether to remove it to support older Python versions, but we will in any case update it only when we add the missing training part of the repo.

In the meanwhile, if you really can't run with a newer python version, an option would be to clone the repo (or fork it) and manually change the few lines where this is happening. 
For example, the line ```head_dim: int | None = 32``` can be modified to ```head_dim = 32``` .

**Comment by tanchihpin0517** [comment]
I see. Perhaps `Optional` or `Union` is an optional solution for this case which preserves the type hint and compatibility for old Python versions. Anyway, appreciate your time to answer. It's definitely a great and impactful work.

**Comment by fosfrancesco** [comment]
Thank you,
And sorry for the delay, but I was on vacation. 
Have a great day!
