### ISSUE TITLE
Augmentations, specifically time warping

### ISSUE THREAD

**Issue by JamesBolt22** [CPJKU/beat_this#7]
Hi, thanks for making this all publicly available it is very helpful.
I am creating the beat and downbeat annotations for your zenodo dataset and I noticed that the time augmented spectrograms do not seem to have lengths that are equal to the percentage increases you state in the paper. Therefore when shifting the beats and downbeats by the same percentages (20, 16, 12, 4 and 8%) it is unclear exactly by how much to change the shifts. Do you have any insight into why these discrepancies occur and how did you shift your beat and downbeat grids for annotating these augmentations?

**Comment by fosfrancesco** [comment]
Hello!
Here is an example of how the stretch changes the spectrogram's size. It will work in the same way for the audio.
I considered a piece from guitarset, since it is the smallest dataset to download.

```
npz = np.load("guitarset.npz")
piece_original = "00_BN1-129-Eb_comp_mix/track"
# the stretched 20 piece
piece_stretched_20 = "00_BN1-129-Eb_comp_mix/track_ts20"
# print both the original and the stretched shapes
print("Original shape", npz[piece_original].shape)
print("Stretched shape", npz[piece_stretched_20].shape)
# the stretched piece is 20% faster, so we scale the tempo by 1.2,
# which means we divide the original size by 1.2
print(npz[piece_original].shape[0] / 1.2)
```

This is basically what we do [in this function](https://github.com/CPJKU/beat_this/blob/d36ee09ccc83b2cfb591960f74afdcf84c6f7824/beat_this/dataset/augment.py#L60) to correctly stretch the beat annotations.

**Comment by JamesBolt22** [comment]
Okay I see, I was multiplying the stretched shape by 0.8 in this case which does not give the correct output. Thank you for the clarification. 

Best.
